name: Test action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job fail
        run: echo "jon fail"; exit 1
  job2:
    runs-on: ubuntu-latest
    steps:     
      - name: Next job
        if: always()
        run: echo "Hello"